name: Quality checks 👌🧪

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    name: Build frontend 🛠️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: example

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v3

      - name: Build Example Project 🛠
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: 'stable'
      - run: flutter pub get
  #    - run: flutter test
      - run: flutter build web

      - name: Upload artifact (Client) ⬆️💻
        uses: actions/upload-artifact@v3.1.1
        with:
          name: example
          path: |
            example/build/web

  pr_context:
    name: Save PR context as artifact
    if: ${{ always() && !cancelled() && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs:
#      - dependency-review
      - build

    steps:
      - name: Save PR context
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_SHA: ${{ github.sha }}
        run: |
          echo $PR_NUMBER > PR_number
          echo $PR_SHA > PR_sha

      - name: Upload PR number as artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: PR_context
          path: |
            PR_number
            PR_sha

  conventional_commits:
    name: Conventional commits check 💬
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v3.2.0

      - name: Check if all commits comply with the specification
        uses: webiny/action-conventional-commits@v1.1.0
