name: Quality checks 👌🧪

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: '30 7 * * 6'
  workflow_dispatch:

jobs:
#  dependency-review:
#    name: Vulnerable dependencies 🔎
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3.2.0
#
#      - name: Scan
#        uses: actions/dependency-review-action@v3.0.2

#  lint:
#    name: Lint 🔬
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout ⬇️
#        uses: actions/checkout@v3.2.0
#
#      - name: Setup node environment ⚙️
#        uses: actions/setup-node@v3.5.1
#        with:
#          node-version: 16
#          cache: 'npm'
#          check-latest: true
#
#      - name: Install dependencies 📦
#        run: npm ci --no-audit
#
#      - name: Run linter ✏️
#        run: 'npm run lint:js && npm run lint:style'

  build:
    name: Build frontend 🛠️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        cache: true
        channel: 'stable'
      working-directory: example
    - run: flutter pub get
#    - run: flutter test
    - run: flutter build web

  pr_context:
    name: Save PR context as artifact
    if: ${{ always() && !cancelled() && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs:
      - dependency-review
      - build

    steps:
      - name: Save PR context
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_SHA: ${{ github.sha }}
        run: |
          echo $PR_NUMBER > PR_number
          echo $PR_SHA > PR_sha

      - name: Upload PR number as artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: PR_context
          path: |
            PR_number
            PR_sha

  conventional_commits:
    name: Conventional commits check 💬
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v3.2.0

      - name: Check if all commits comply with the specification
        uses: webiny/action-conventional-commits@v1.1.0
